// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'nb'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	contact: {
		/**
		 * C​o​n​t​a​c​t​ ​u​s
		 */
		title: string
		/**
		 * A​d​d​r​e​s​s
		 */
		addressTitle: string
		/**
		 * E​m​a​i​l
		 */
		emailTitle: string
		/**
		 * P​h​o​n​e
		 */
		phoneTitle: string
	}
	meta: {
		/**
		 * A​u​r​o​r​a​k​l​i​n​i​k​k​e​n​ ​p​r​o​v​i​d​e​s​ ​c​e​t​a​m​i​n​e​ ​t​r​e​a​t​m​e​n​t​ ​f​o​r​ ​d​e​p​r​e​s​s​i​o​n​ ​i​n​ ​O​s​l​o
		 */
		description: string
	}
	faq: {
		/**
		 * Q​u​e​s​t​i​o​n​s​ ​&​a​m​p​;​ ​A​n​s​w​e​r​s
		 */
		title: string
	}
	/**
	 * G​o​ ​t​o​ ​b​o​o​k​i​n​g
	 */
	goToBookingPage: string
	/**
	 * O​u​r​ ​s​e​r​v​i​c​e​s
	 */
	ourServices: string
	/**
	 * H​o​m​e
	 */
	homeTitle: string
}

export type TranslationFunctions = {
	contact: {
		/**
		 * Contact us
		 */
		title: () => LocalizedString
		/**
		 * Address
		 */
		addressTitle: () => LocalizedString
		/**
		 * Email
		 */
		emailTitle: () => LocalizedString
		/**
		 * Phone
		 */
		phoneTitle: () => LocalizedString
	}
	meta: {
		/**
		 * Auroraklinikken provides cetamine treatment for depression in Oslo
		 */
		description: () => LocalizedString
	}
	faq: {
		/**
		 * Questions &amp; Answers
		 */
		title: () => LocalizedString
	}
	/**
	 * Go to booking
	 */
	goToBookingPage: () => LocalizedString
	/**
	 * Our services
	 */
	ourServices: () => LocalizedString
	/**
	 * Home
	 */
	homeTitle: () => LocalizedString
}

export type Formatters = {}
